#!/bin/python3
import os
import sys

# cd to rootProject dir
SCRIPT_PATH = os.path.realpath(__file__)
SCRIPT_DIR = os.path.dirname(SCRIPT_PATH)
os.chdir(SCRIPT_DIR)
os.chdir("../../")
ROOT_PROJECT_PATH = os.getcwd()
# Now we are at rootProject directory. Let's do this.

sys.path.append('deploy')
from version_retriever import getVersion

VERSION = getVersion()
NSIS_PATH = os.path.join("deploy", "windows", "nsis.nsi")

fileLines = []
with open(NSIS_PATH, "r") as file:
	fileLines = file.readlines()

with open(NSIS_PATH, "w") as file:
	for fileLine in fileLines:
		if fileLine.startswith("!define APP_VERSION"):
			fileLine = "!define APP_VERSION \""+VERSION+"\" ; Generated by version.py\n"
		file.write(fileLine)
