/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app.shamilton.timecard

import app.shamilton.timecard.command.CommandList
import app.shamilton.timecard.command.ICommand

class App() {

	val NAME = "timecard"
	val VERSION = "0.0.1-DEV"
	val AUTHOR = "stephen-hamilton-c"
	val ARGS: List<String>
		get() = _args

	companion object {
		private var _args: List<String> = listOf()
	}

	constructor(args: Array<String>): this() {
		_args = args.asList()
	}

}

fun main(args: Array<String>) {
	App(args)
	val commandName: String = if(args.isNotEmpty()) args[0].uppercase() else "STATUS"
	val foundCommand: ICommand? = CommandList.COMMANDS.find { it.m_Name == commandName }
	foundCommand?.execute() ?: println("Unknown command. Use 'timecard help' for a list of commands.")
}
