/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app.shamilton.adhdtimecard;

import java.io.File;
import app.shamilton.adhdtimecard.core.TimeEntries;
import app.shamilton.adhdtimecard.core.TimeEntry;

fun main(args: Array<String>) {
	// KotlinJsonAdapterFactory is apparently deprecated, saying it has been moved...
	// Doesn't say where, and I can't find any docs on this. Too bad.
	val oldEntries = TimeEntries.loadFromFile();
	println("old entries: ${oldEntries.toString()}");

	val entries = TimeEntries(mutableListOf(TimeEntry(0, 30), TimeEntry(60, 0)));
	entries.saveToFile();
}
