/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app.shamilton.adhdtimecard;

import java.io.File;
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.temporal.TemporalUnit
import app.shamilton.adhdtimecard.core.TimeEntries;
import app.shamilton.adhdtimecard.core.TimeEntry;
import app.shamilton.adhdtimecard.command.*;

fun getCommand(commands: List<Command>, cmdInput: String): Command {
	for(command in commands) {
		if(command.m_name == cmdInput || command.m_alias == cmdInput){
			return command;
		}
	}

	return HelpCommand(commands);
}

fun main(args: Array<String>) {
	println("args: ${args.joinToString()}");
	println();

	val timeEntries = TimeEntries.loadFromFile();
	val commands: List<Command> = listOf(
		ClockInCommand(timeEntries),
		ClockOutCommand(timeEntries)
	)
	
	val cmdInput: String = args[0].lowercase();
	var selectedCommand: Command = getCommand(commands, cmdInput);
	selectedCommand.execute();

	timeEntries.saveToFile();
}
